"""Add init data

Revision ID: 3647de328754
Revises: ee26bc9a8ad0
Create Date: 2025-07-22 02:41:21.254580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3647de328754'
down_revision = 'ee26bc9a8ad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(
        sa.Table(
            'books',
            sa.MetaData(),
            sa.Column('id', sa.Integer(),primary_key=True),
            sa.Column('title', sa.String(length=120), nullable=False),
            sa.Column('author', sa.String(length=120), nullable=False),
            sa.Column('pages', sa.Integer(), nullable=False),
            sa.Column('rating', sa.Float(), nullable=True),
            sa.Column('price', sa.Numeric(), nullable=False),
        ),
        [
            {'title': 'To Kill a Mockingbird', 'author': 'Harper Lee', 'pages': 324, 'rating': 4.8, 'price': 14.99},
            {'title': '1984', 'author': 'George Orwell', 'pages': 328, 'rating': 4.7, 'price': 12.95},
            {'title': 'Animal Farm', 'author': 'George Orwell', 'pages': 112, 'rating': 4.6, 'price': 8.99},
            {'title': 'Pride and Prejudice', 'author': 'Jane Austen', 'pages': 279, 'rating': 4.6, 'price': 9.99},
            {'title': 'The Great Gatsby', 'author': 'F. Scott Fitzgerald', 'pages': 180, 'rating': 4.4, 'price': 10.99}
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM books")
    # ### end Alembic commands ###
